CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  due_date DATE,
  priority VARCHAR(10) NOT NULL DEFAULT 'medium',
  category VARCHAR(50) NOT NULL DEFAULT 'Other',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);